lib/akedia_web/router.ex
defmodule AkediaWeb.Router do
  use AkediaWeb, :router

  import Phoenix.LiveView.Router
  import AkediaWeb.Plugs.PlugUser
  import AkediaWeb.Plugs.PlugFormat

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :check_loggedin
    plug :assign_user
    plug :refresh_user
    plug :put_root_layout, {AkediaWeb.LayoutView, :root}
  end

  pipeline :activitypub do
    plug :accepts, ~w(html json jsonap jsonld)
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :check_loggedin
    plug :assign_user
    plug :refresh_user
    plug :put_req_format
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
  end

  pipeline :auth do
    plug :check_user
  end

  # -----------------------------------------------------
  # Public Routes
  # -----------------------------------------------------

  scope "/", AkediaWeb do
    pipe_through [:browser]

    get "/", PublicController, :index
    get "/new", PublicController, :new

    get "/tagged-with/:topic", PublicController, :tagged
    get "/search", PublicController, :search
    get "/feed", AtomController, :index

    resources "/posts", PostController
    resources "/bookmarks", BookmarkController
    resources "/images", ImageController
    resources "/likes", LikeController
    resources "/topics", TopicController

    scope "/auth" do
      get "/register", UserController, :new
      post "/register", UserController, :create

      get "/login", SessionController, :new
      post "/login", SessionController, :create

      get "/two_factor", SessionController, :two_factor
      post "/webauthn", SessionController, :webauthn_create
      post "/totp", SessionController, :totp_create

      delete "/logout", SessionController, :delete
    end

    scope "/.well-known" do
      get "/webfinger", WellKnownController, :webfinger
      get "/host-meta", WellKnownController, :host_meta
    end
  end

  scope "/", AkediaWeb do
    pipe_through :activitypub

    get "/user", UserController, :show
    get "/inbox", InboxController, :index
    get "/outbox", OutboxController, :index
  end

  # -----------------------------------------------------
  # Protected Routes
  # -----------------------------------------------------

  scope "/user", AkediaWeb do
    pipe_through [:browser, :auth]

    resources "/", UserController, only: [:edit, :update], singleton: true
    resources "/profiles", ProfileController
    get "/security", UserController, :security
  end

  scope "/admin", AkediaWeb do
    pipe_through [:browser, :auth]

    get "/mentions", MentionController, :index

    scope "/queue" do
      get "/", QueueController, :index
      get "/drafts", QueueController, :drafts
      get "/jobs", QueueController, :jobs
    end
  end

  # -----------------------------------------------------
  # API Routes
  # -----------------------------------------------------

  scope "/api" do
    pipe_through [:api]

    scope "/webauthn" do
      post "/", AkediaWeb.WebauthnController, :create
      post "/callback", AkediaWeb.WebauthnController, :callback
      post "/session_callback", AkediaWeb.SessionController, :webauthn_callback
    end

    scope "/indie" do
      forward "/micropub",
              PlugMicropub,
              handler: Akedia.Indie.Micropub.Handler,
              json_encoder: Phoenix.json_library()

      forward "/webmention",
              AkediaWeb.Plugs.PlugWebmention,
              handler: Akedia.Webmentions.Handler,
              json_encoder: Phoenix.json_library()
    end
  end
end

lib/akedia_web/controllers/queue_controller.ex
defmodule AkediaWeb.QueueController do
  use AkediaWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def drafts(conn, _params) do
    drafts = Akedia.Content.list_drafted_posts()

    render(conn, "drafts.html", posts: drafts)
  end

  def jobs(conn, _params) do
    failed_jobs = Akedia.Jobs.list_failed_jobs()
    completed_jobs = Akedia.Jobs.list_completed_jobs()

    render(conn, "jobs.html", failed_jobs: failed_jobs, completed_jobs: completed_jobs)
  end
end

lib/akedia_web/views/queue_view.ex
defmodule AkediaWeb.QueueView do
  use AkediaWeb, :view
end

lib/akedia_web/templates/queue/drafts.html.eex
<div class="columns">
  <div class="column is-3">
    <%= render "sidebar.html", assigns %>
  </div>
  <div class="column">
    <%= for post <- @posts do %>
      <article class="card">
        <div class="card-content">
          <h3 class="title"><%= post.title || "No Title" %></h3>
          <%= link post.inserted_at, to: Routes.post_path(@conn, :show, post), class: "subtitle" %>
        </div>
      </article>
    <% end %>
  </div>
</div>

lib/akedia_web/templates/queue/index.html.eex
<div class="columns">
  <div class="column is-3">
    <%= render "sidebar.html", assigns %>
  </div>
  <div class="column">
    <div class="card">
    	<div class="card-content">
    		<div class="title">here be dragons</div>
    	</div>
    </div>
  </div>
</div>

lib/akedia_web/templates/queue/jobs.html.eex
<div class="columns">
  <div class="column is-3">
    <%= render "sidebar.html", assigns %>
  </div>
  <div class="column">
    
      <div class="card">
        <div class="card-content">
          <%= if Enum.empty?(@failed_jobs) do %>
          No jobs in queue, sorry.
          <% end %>

          <%= for job <- @failed_jobs do %>
            <%= job.worker %> @ <%= job.state %>
            <span class="has-text-grey"><%= job.state %></span>
          <% end %>
        </div>
      </div>

      <div class="card">
        <div class="card-content">
          <%= for job <- @completed_jobs do %>
            <%= job.worker %> <span class="has-text-success"><%= job.state %></span>
            <time datetime="<%= job.completed_at %>"><%= Timex.from_now(job.completed_at) %></time>
          <% end %>
        </div>
      </div>
    
    
  </div>
</div>

lib/akedia_web/templates/queue/sidebar.html.eex
<div class="card">
  <div class="card-content">
    <aside class="menu">
      <ul class="menu-list">
        <%= active_link @conn, to: Routes.queue_path(@conn, :index), wrap_tag: :li do %>
          <span>Inbox</span>
        <% end %>
        <%= active_link @conn, to: Routes.queue_path(@conn, :drafts), wrap_tag: :li do %>
          <span>Drafts</span>
        <% end %>
        <%= active_link @conn, to: Routes.queue_path(@conn, :jobs), wrap_tag: :li do %>
          <span>Jobs</span>
        <% end %>
      </ul>
    </aside>
  </div>
</div>