lib/akedia_web/router.ex
defmodule AkediaWeb.Router do
  use AkediaWeb, :router

  import Phoenix.LiveView.Router
  import AkediaWeb.Plugs.PlugUser
  import AkediaWeb.Plugs.PlugFormat

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :check_loggedin
    plug :assign_user
    plug :refresh_user
    plug :put_root_layout, {AkediaWeb.LayoutView, :root}
  end

  pipeline :activitypub do
    plug :accepts, ~w(html json jsonap jsonld)
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :check_loggedin
    plug :assign_user
    plug :refresh_user
    plug :put_req_format
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
  end

  pipeline :auth do
    plug :check_user
  end

  # -----------------------------------------------------
  # Public Routes
  # -----------------------------------------------------

  scope "/", AkediaWeb do
    pipe_through [:browser]

    get "/", PublicController, :index
    get "/new", PublicController, :new

    get "/tagged-with/:topic", PublicController, :tagged
    get "/search", PublicController, :search
    get "/feed", AtomController, :index

    resources "/posts", PostController
    resources "/bookmarks", BookmarkController
    resources "/images", ImageController
    resources "/likes", LikeController
    resources "/topics", TopicController

    scope "/auth" do
      get "/register", UserController, :new
      post "/register", UserController, :create

      get "/login", SessionController, :new
      post "/login", SessionController, :create

      get "/two_factor", SessionController, :two_factor
      post "/webauthn", SessionController, :webauthn_create
      post "/totp", SessionController, :totp_create

      delete "/logout", SessionController, :delete
    end

    scope "/.well-known" do
      get "/webfinger", WellKnownController, :webfinger
      get "/host-meta", WellKnownController, :host_meta
    end
  end

  scope "/", AkediaWeb do
    pipe_through :activitypub

    get "/user", UserController, :show
    get "/inbox", InboxController, :index
    get "/outbox", OutboxController, :index
  end

  # -----------------------------------------------------
  # Protected Routes
  # -----------------------------------------------------

  scope "/user", AkediaWeb do
    pipe_through [:browser, :auth]

    resources "/", UserController, only: [:edit, :update], singleton: true
    resources "/profiles", ProfileController
    get "/security", UserController, :security
  end

  scope "/admin", AkediaWeb do
    pipe_through [:browser, :auth]

    get "/mentions", MentionController, :index

    scope "/queue" do
      get "/", QueueController, :index
      get "/drafts", QueueController, :drafts
      get "/jobs", QueueController, :jobs
    end
  end

  # -----------------------------------------------------
  # API Routes
  # -----------------------------------------------------

  scope "/api" do
    pipe_through [:api]

    scope "/webauthn" do
      post "/", AkediaWeb.WebauthnController, :create
      post "/callback", AkediaWeb.WebauthnController, :callback
      post "/session_callback", AkediaWeb.SessionController, :webauthn_callback
    end

    scope "/indie" do
      forward "/micropub",
              PlugMicropub,
              handler: Akedia.Indie.Micropub.Handler,
              json_encoder: Phoenix.json_library()

      forward "/webmention",
              AkediaWeb.Plugs.PlugWebmention,
              handler: Akedia.Webmentions.Handler,
              json_encoder: Phoenix.json_library()
    end
  end
end

lib/akedia_web/views/layout_view.ex
defmodule AkediaWeb.LayoutView do
  use AkediaWeb, :view

  def version do
    Application.spec(:akedia, :vsn)
  end

  @doc """
  Generates path for the JavaScript view we want to use
  in this combination of view/template.
  """
  def js_view_path(conn) do
    [controller_name(conn), action_name(conn)]
    |> Enum.join("/")
  end

  # Takes the resource name of the view module and removes the
  # the ending *_view* string.
  defp controller_name(%{private: private} = _conn) do
    private
    |> Map.get(:phoenix_controller)
    |> Phoenix.Naming.resource_name()
    |> String.replace("_controller", "")
  end

  # Removes the extion from the template and reutrns
  # just the name.
  defp action_name(%{private: private} = _conn) do
    private
    |> Map.get(:phoenix_action)
    |> to_string()
  end
end

lib/akedia_web/templates/layout/app.html.eex
<main id="content">
  <p class="notification is-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="notification is-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/akedia_web/templates/layout/app_wide.html.eex
<main id="content" class="wide">
  <p class="notification is-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="notification is-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/akedia_web/templates/layout/bare.html.eex
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Register</title>

    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <div class="container">
      <%= render @view_module, @view_template, assigns %>
    </div>
  </body>
</html>

lib/akedia_web/templates/layout/footer.html.eex
<p class="info clearfix has-text-grey">&copy; 2019 - 2020 by <%= @current_user.name %> • Powered by <a href="https://github.com/inhji/akedia" target="_blank" rel="noreferrer" class="has-text-grey-light">Akedia v<%= version() %></a></p>

lib/akedia_web/templates/layout/navigation.html.eex
<nav class="navbar is-fixed-top">
  <div class="navbar-brand">     
    <%= link to: Routes.public_path(@conn, :index),
        class: "navbar-item is-expanded" do %>
        <span class="icon site-logo">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512">
            <path d="M537.6 226.6c4.1-10.7 6.4-22.4 6.4-34.6 0-53-43-96-96-96-19.7 0-38.1 6-53.3 16.2C367 64.2 315.3 32 256 32c-88.4 0-160 71.6-160 160 0 2.7.1 5.4.2 8.1C40.2 219.8 0 273.2 0 336c0 79.5 64.5 144 144 144h368c70.7 0 128-57.3 128-128 0-61.9-44-113.6-102.4-125.4z"/>
          </svg>
        </span>
    <% end %>
    <div class="navbar-burger burger" data-target="mainNav">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="mainNav" class="navbar-menu">

    <%= if @logged_in do %>
    <div class="navbar-start">
      <%= link "NEw", to: Routes.public_path(@conn, :new), class: "navbar-item" %>
    </div>
    <% end %>
    
    <div class="navbar-end">
      <%= form_for @conn, Routes.public_path(@conn, :search), [method: :get, class: "navbar-item navbar-search"], fn f -> %>
        <div class="field">
          <p class="control">
            <%= search_input f, :query, class: "input is-rounded", placeholder: "Here be dragons.. 🐉" %>
          </p>
        </div>
      <% end %>

      <%= if not @logged_in do %>
        <%= link "Login", to: Routes.session_path(@conn, :new), class: "navbar-item" %>
      <% else %>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link" href="<%= Routes.user_path(@conn, :show) %>">
            <span class="icon">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 495 512"><path d="M248 104c-53 0-96 43-96 96s43 96 96 96 96-43 96-96-43-96-96-96zm0 144c-26.5 0-48-21.5-48-48s21.5-48 48-48 48 21.5 48 48-21.5 48-48 48zm0-240C111 8 0 119 0 256s111 248 248 248 248-111 248-248S385 8 248 8zm0 448c-49.7 0-95.1-18.3-130.1-48.4 14.9-23 40.4-38.6 69.6-39.5 20.8 6.4 40.6 9.6 60.5 9.6s39.7-3.1 60.5-9.6c29.2 1 54.7 16.5 69.6 39.5-35 30.1-80.4 48.4-130.1 48.4zm162.7-84.1c-24.4-31.4-62.1-51.9-105.1-51.9-10.2 0-26 9.6-57.6 9.6-31.5 0-47.4-9.6-57.6-9.6-42.9 0-80.6 20.5-105.1 51.9C61.9 339.2 48 299.2 48 256c0-110.3 89.7-200 200-200s200 89.7 200 200c0 43.2-13.9 83.2-37.3 115.9z"/></svg>
            </span>
            <span><%= @current_user.name %></span>
          </a>

          <div class="navbar-dropdown is-boxed">
            <%= link "Topics", to: Routes.topic_path(@conn, :index), class: "navbar-item" %>
            <%= link "Inbox", to: Routes.queue_path(@conn, :index), class: "navbar-item" %>
            <hr class="navbar-divider">
            <%= link "Identities", to: Routes.profile_path(@conn, :index), class: "navbar-item" %>
            <%= link "Edit User", to: Routes.user_path(@conn, :edit), class: "navbar-item" %>
            <%= link "Security", to: Routes.user_path(@conn, :security), class: "navbar-item" %>
            <hr class="navbar-divider">
            <%= link "Logout", to: Routes.session_path(@conn, :delete), method: "delete", data: [confirm: "ಥ‿ಥ\nR u sure?"], class: "navbar-item" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>

lib/akedia_web/templates/layout/root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <%= live_title_tag assigns[:page_title] || "Home", suffix: " - Akedia" %>

    <%= if @has_user do %>
      <%= for profile <- @current_user.profiles do %>
        <link rel="<%= profile.rel_value %>" href="<%= profile.url %>" />
      <% end %>
    <% end %>

    <link rel="apple-touch-icon" sizes="180x180" href="<%= Routes.static_path(@conn, "/images/favicon/apple-touch-icon.png") %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= Routes.static_path(@conn, "/images/favicon/favicon-32x32.png") %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= Routes.static_path(@conn, "/images/favicon/favicon-16x16.png") %>">
    <link rel="mask-icon" href="<%= Routes.static_path(@conn, "/images/favicon/safari-pinned-tab.svg") %>" color="#4c00ff">
    <link rel="manifest" href="<%= Routes.static_path(@conn, "/site.webmanifest") %>">
    <meta name="msapplication-TileColor" content="#4c00ff">
    <meta name="theme-color" content="#4c00ff">

    <%= csrf_meta_tag() %>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>

  <body class="has-navbar-fixed-top" data-js-view-path="<%= js_view_path(@conn) %>"> 
    <header>
      <nav role="navigation" class="main-nav" id="main-nav">
        <%= render "navigation.html", assigns %>
      </nav>
    </header>

    <%= @inner_content %>

    <footer class="footer" id="footer">
      <%= render "footer.html", assigns %>
    </footer>
  </body>
</html>