lib/akedia_web/router.ex
defmodule AkediaWeb.Router do
  use AkediaWeb, :router

  import Phoenix.LiveView.Router
  import AkediaWeb.Plugs.PlugUser
  import AkediaWeb.Plugs.PlugFormat

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :check_loggedin
    plug :assign_user
    plug :refresh_user
    plug :put_root_layout, {AkediaWeb.LayoutView, :root}
  end

  pipeline :activitypub do
    plug :accepts, ~w(html json jsonap jsonld)
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :check_loggedin
    plug :assign_user
    plug :refresh_user
    plug :put_req_format
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
  end

  pipeline :auth do
    plug :check_user
  end

  # -----------------------------------------------------
  # Public Routes
  # -----------------------------------------------------

  scope "/", AkediaWeb do
    pipe_through [:browser]

    get "/", PublicController, :index
    get "/new", PublicController, :new

    get "/tagged-with/:topic", PublicController, :tagged
    get "/search", PublicController, :search
    get "/feed", AtomController, :index

    resources "/posts", PostController
    resources "/bookmarks", BookmarkController
    resources "/images", ImageController
    resources "/likes", LikeController
    resources "/topics", TopicController

    scope "/auth" do
      get "/register", UserController, :new
      post "/register", UserController, :create

      get "/login", SessionController, :new
      post "/login", SessionController, :create

      get "/two_factor", SessionController, :two_factor
      post "/webauthn", SessionController, :webauthn_create
      post "/totp", SessionController, :totp_create

      delete "/logout", SessionController, :delete
    end

    scope "/.well-known" do
      get "/webfinger", WellKnownController, :webfinger
      get "/host-meta", WellKnownController, :host_meta
    end
  end

  scope "/", AkediaWeb do
    pipe_through :activitypub

    get "/user", UserController, :show
    get "/inbox", InboxController, :index
    get "/outbox", OutboxController, :index
  end

  # -----------------------------------------------------
  # Protected Routes
  # -----------------------------------------------------

  scope "/user", AkediaWeb do
    pipe_through [:browser, :auth]

    resources "/", UserController, only: [:edit, :update], singleton: true
    resources "/profiles", ProfileController
    get "/security", UserController, :security
  end

  scope "/admin", AkediaWeb do
    pipe_through [:browser, :auth]

    get "/mentions", MentionController, :index

    scope "/queue" do
      get "/", QueueController, :index
      get "/drafts", QueueController, :drafts
      get "/jobs", QueueController, :jobs
    end
  end

  # -----------------------------------------------------
  # API Routes
  # -----------------------------------------------------

  scope "/api" do
    pipe_through [:api]

    scope "/webauthn" do
      post "/", AkediaWeb.WebauthnController, :create
      post "/callback", AkediaWeb.WebauthnController, :callback
      post "/session_callback", AkediaWeb.SessionController, :webauthn_callback
    end

    scope "/indie" do
      forward "/micropub",
              PlugMicropub,
              handler: Akedia.Indie.Micropub.Handler,
              json_encoder: Phoenix.json_library()

      forward "/webmention",
              AkediaWeb.Plugs.PlugWebmention,
              handler: Akedia.Webmentions.Handler,
              json_encoder: Phoenix.json_library()
    end
  end
end

lib/akedia/accounts/user.ex
defmodule Akedia.Accounts.User do
  use Ecto.Schema
  use Waffle.Ecto.Schema
  import Ecto.Changeset
  alias Akedia.Accounts.{Credential, Profile}
  alias AkediaWeb.Router.Helpers, as: Routes

  schema "users" do
    field :name, :string
    field :username, :string

    field :tagline, :string, default: ""
    field :about, :string, default: ""
    field :now, :string, default: ""

    field :avatar, Akedia.Accounts.AvatarUploader.Type
    field :cover, Akedia.Accounts.CoverUploader.Type

    field :priv_key, :string
    field :pub_key, :string

    has_one(:credential, Credential)
    has_many(:profiles, Profile)

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :username, :now, :about, :tagline, :priv_key, :pub_key])
    |> cast_attachments(attrs, [:avatar, :cover])
    |> maybe_generate_pub_key_pair()
    |> validate_required([:name, :username, :priv_key, :pub_key])
    |> unique_constraint(:username)
  end

  @doc """
  Returns the actor url
  """
  def actor_url(), do: Routes.user_url(AkediaWeb.Endpoint, :show)

  @doc """
  Returns the inbox url
  """
  def inbox_url(), do: Routes.inbox_url(AkediaWeb.Endpoint, :index)

  @doc """
  Returns the outbox url
  """
  def outbox_url(), do: Routes.outbox_url(AkediaWeb.Endpoint, :index)

  @doc """
  Returns the public key url
  """
  def pubkey_url(), do: actor_url() <> "#main-key"

  @doc """
  Returns the user as an activity pub actor. Context needs to be added via `Akedia.Helpers.with_context/1` or `Akedia.Helpers.with_context/2`

  ## Examples

  ```
  {
    "icon": {
      "mediaType": "image/png",
      "type": "Image",
      "url": "http://localhost:4000/uploads/user/me_thumb.png?v=63746169254"
    },
    "id": "http://localhost:4000/about",
    "name": "Inhji",
    "preferredUsername": "inhji",
    "publicKey": {
      "id": "http://localhost:4000/about#main-key",
      "owner": "http://localhost:4000/about",
      "publicKeyPem": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA29XxA2UamqFZFuX9zwpU\neVC+zFRgSkDeTVAjdKbddDbTi0nXVbxQepVsvjG86jdj7v9XKNm3PfB54zJWGJ/8\nQ/rTK19TXwGsGrBBGvSl4asIn8erQQkWDhlzyghOpNznquunbXvt0KQRkcaXg6r2\nsQluKCTmV3NV+RpynlZd+OSZDyqBKmnzKbFAk5R1F05hyoANy9ogp6Ogae0vGkGJ\nOseOaam6HuXD1oOvd262BjfKVH0L9Y4wsb9yao7kAKNSTauyvfTkIuy9dv1qh1cj\ns+a41L+SnLMGMtMa/tERhl4sYglHzPAUrn2rSTpEM9+yMvsbph/khRkU3aMN36ov\nfQIDAQAB\n-----END PUBLIC KEY-----\n"
    },
    "summary": "*daydreamer*. \r\ntinkerer. depressionist. overthinker. rebel without a voice. bruhgrammer. catlover. slightly human.",
    "type": "Person"
  }
  ```

  """
  def to_json(%Akedia.Accounts.User{} = user) do
    %{
      "id" => actor_url(),
      "type" => "Person",
      "preferredUsername" => user.username,
      "name" => user.name,
      "summary" => user.tagline,
      "inbox" => inbox_url(),
      "outbox" => outbox_url(),
      # "followers" => follower_url(),
      # "following" => following_url(),
      "publicKey" => %{
        "id" => pubkey_url(),
        "owner" => actor_url(),
        "publicKeyPem" => user.pub_key
      },
      "icon" => %{
        "mediaType" => MIME.type("png"),
        "url" => Akedia.url(AkediaWeb.Helpers.Media.avatar_url(user)),
        "type" => "Image"
      }
    }
  end

  @doc false
  defp maybe_generate_pub_key_pair(changeset) do
    case get_field(changeset, :priv_key) do
      nil ->
        {:ok, {priv, pub}} = RsaEx.generate_keypair()

        changeset
        |> put_change(:priv_key, priv)
        |> put_change(:pub_key, pub)

      _ ->
        changeset
    end
  end
end

lib/akedia_web/controllers/user_controller.ex
defmodule AkediaWeb.UserController do
  use AkediaWeb, :controller

  alias Akedia.{Accounts, Repo, Auth}
  alias Akedia.Accounts.User
  import Akedia.Helpers, only: [with_context: 1]

  def new(conn, _params) do
    changeset = Accounts.change_user(%Accounts.User{})

    conn
    |> put_layout("bare.html")
    |> render("new.html", changeset: changeset)
  end

  def create(conn, %{"user" => %{"credential" => credential_params} = user_params}) do
    case Accounts.count_users() do
      0 ->
        case Accounts.create_user(user_params) do
          {:ok, user} ->
            user
            |> Ecto.build_assoc(:credential)
            |> Accounts.change_credential(credential_params)
            |> Repo.insert!()

            conn
            |> Auth.login(user)
            |> put_flash(:info, "Welcome #{user.name}.")
            |> redirect(to: Routes.public_path(conn, :index))

          {:error, %Ecto.Changeset{} = changeset} ->
            render(conn, "new.html", changeset: changeset)
        end

      _ ->
        conn
        |> put_view(ErrorView)
        |> render("register.html")
    end
  end

  def show(%{private: %{plug_format: "html"}} = conn, _params) do
    user = Accounts.get_user!()
    render(conn, "show.html", user: user)
  end

  def show(%{private: %{plug_format: "json" <> _rest}} = conn, _params) do
    user = Accounts.get_user!()
    json = User.to_json(user)
    json(conn, with_context(json))
  end

  def edit(conn, _params) do
    user = Accounts.get_user!()
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"user" => %{"credential" => credential_params} = user_params}) do
    user = Accounts.get_user!()

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        credential = Accounts.get_credential_by_user(user.id)
        Accounts.update_credential(credential, credential_params)

        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def security(conn, _params) do
    user = Akedia.Accounts.get_user!()
    issuer = user.username
    email = user.credential.email

    qr_code =
      Akedia.Config.get(:totp_secret)
      |> Base.encode32()
      |> totp_qr_string(issuer, email)
      |> QRCode.QR.create!()
      |> QRCode.Svg.to_base64()

    render(conn, "security.html", qr_code: qr_code)
  end

  defp totp_qr_string(secret, issuer, email) do
    "otpauth://totp/#{issuer}:#{email}?secret=#{secret}&issuer=#{issuer}&algorithm=SHA1&digits=6&period=30"
  end
end

lib/akedia_web/views/user_view.ex
defmodule AkediaWeb.UserView do
  use AkediaWeb, :view

  def render("meta.show.html", assigns) do
    [title("User", assigns)]
  end

  def render("meta.edit.html", assigns) do
    [title("Edit user", assigns)]
  end
end

lib/akedia_web/templates/user/edit.html.eex
<div class="card">
	<div class="card-content">
		<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update)) %>
	</div>
</div>

lib/akedia_web/templates/user/form.html.eex
<%= form_for @changeset, @action, [multipart: true, class: "form user"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="field">
    <%= label f, :name, class: "label" %>
    <div class="control">
      <%= text_input f, :name, class: "input" %>
    </div>
    <%= error_tag f, :name %>
  </div>

  <div class="field">
    <%= label f, :username, class: "label" %>
    <div class="control">
      <%= text_input f, :username, class: "input" %>
    </div>
    <%= error_tag f, :username %>
  </div>

  <%= inputs_for f, :credential, fn fc -> %>
    <div class="field">
      <%= label fc, :email, class: "label" %>
      <div class="control">
        <%= text_input fc, :email, class: "input" %>
      </div>
      <%= error_tag fc, :email %>
    </div>
  <% end %>

  <div class="field">
    <%= label f, :tagline, class: "label" %>
    <div class="control">
      <%= textarea f, :tagline, class: "textarea" %>
    </div>
    <%= error_tag f, :tagline %>
  </div>

  <div class="field">
    <%= label f, :now, class: "label" %>
    <div class="zen">
      <input type="checkbox" id="zen-toggle-comment">
      <%= label f, :now, class: "label" %>
      <div class="zen-backdrop">
        <%= textarea f, :now,
            class: "textarea",
            rows: 5 %>
        <label for="zen-toggle-comment">Zen Mode</label>
      </div>
    </div>
    <%= error_tag f, :now %>
  </div>

  <div class="field">
    <%= label f, :about, class: "label" %>
    <div class="zen">
      <input type="checkbox" id="zen-toggle-comment">
      <%= label f, :about, class: "label" %>
      <div class="zen-backdrop">
        <%= textarea f, :about,
            class: "textarea",
            rows: 5 %>
        <label for="zen-toggle-comment">Zen Mode</label>
      </div>
    </div>
    <%= error_tag f, :about %>
  </div>

  <div class="columns">
    <div class="column">
     <img src=" <%= avatar_url(@user) %>" style="max-width: 100%">

      <div class="field">
        <%= label f, :avatar, class: "label" %>
        <div class="file">
          <label class="file-label">
            <%= file_input f, :avatar, class: "file-input" %>
            <span class="file-cta">
              <span class="file-icon">
                <i class="fa fa-upload"></i>
              </span>
              <span class="file-label">
                Choose a file…
              </span>
            </span>
          </label>
        </div>
      </div>
    </div>
    <div class="column">
      <img src=" <%= cover_url(@user) %>" style="max-width: 100%">

      <div class="field">
        <%= label f, :cover, class: "label" %>
        <div class="file">
          <label class="file-label">
            <%= file_input f, :cover, class: "file-input" %>
            <span class="file-cta">
              <span class="file-icon">
                <i class="fa fa-upload"></i>
              </span>
              <span class="file-label">
                Choose a file…
              </span>
            </span>
          </label>
        </div>
      </div>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= submit "Save", class: "button is-success" %>
    </div>
  </div>


<% end %>

lib/akedia_web/templates/user/form_register.html.eex
<%= form_for @changeset, @action, [class: "form register"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="field">
    <%= label f, :name %>
    <%= text_input f, :name, class: "input" %>
    <%= error_tag f, :name %>
  </div>

  <div class="field">
    <%= label f, :username %>
    <%= text_input f, :username, class: "input" %>
    <%= error_tag f, :username %>
  </div>

  <%= inputs_for f, :credential, fn fc -> %>
    <div class="field">
      <%= label fc, :email %>
      <%= text_input fc, :email, class: "input" %>
      <%= error_tag fc, :email %>
    </div>

    <div class="field">
      <%= label fc, :password %>
      <%= password_input fc, :encrypted_password, class: "input" %>
      <%= error_tag fc, :encrypted_password %>
    </div>
  <% end %>

  <div class="field">
    <%= submit "Register", class: "button is-success" %>
  </div>
<% end %>

lib/akedia_web/templates/user/new.html.eex
<div class="columns">
  <div class="column">
    <h1 class="title">Register</h1>

    <%= render "form_register.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>
  </div>
</div>

lib/akedia_web/templates/user/security.html.eex
<h1 class="title">Security</h1>

<div class="card">
	<div class="card-content">
		<h2 class="subtitle">Webauthn</h2>

		<div class="content" style="word-wrap: break-word;">
			<dl>
				<dt>Device</dt>
				<dd><%= @current_user.credential.device_name %></dd>
				<dt>External Id</dt>
				<dd><%= String.slice(@current_user.credential.external_id, 0..999) %></dd>
				<dt>Public Key</dt>
				<dd><%= String.slice(@current_user.credential.public_key, 0..999) %></dd>
			</dl>			
		</div>

		<%= form_for @conn, Routes.webauthn_path(@conn, :create), [id: "registration-create", class: "form"], fn f -> %>
			<div class="field">
				<%= label f, :device_name, "Register a new device", class: "label" %>
				<%= text_input f, :device_name, class: "input" %>
			</div>
			<%= submit "Register", class: "button is-primary" %>
		<% end %>
	</div>
</div>

<div class="spacer"></div>

<div class="card">
	<div class="card-content">
		<h2 class="subtitle">TOTP</h2>

		<img src='data:image/svg+xml; base64, <%= @qr_code %>' width="200" />
	</div>
</div>

lib/akedia_web/templates/user/show.html.eex
<%= render SharedView, "hcard.html", assigns %>

<div class="spacer"></div>

<div class="card">
	<div class="card-content">
		<h2 class="title">About Me</h1>

		<div class="content">
			<%= to_html(@current_user.about) %>
		</div>

		<h2 class="title"><a name="now">Nowww</a></h2>

		<div class="content">
			<%= to_html(@current_user.now) %>
		</div>

		<h2 class="title">About this Site</h2>

		<div class="content">
			<ul>
				<li>Weather Data powered by <a href="https://darksky.net">DarkSky</a></li>
				<li>Weather Icons by <a href="https://github.com/darkskyapp/skycons">@darkskyapp</a> with color modifications by <a href="https://github.com/maxdow/skycons">@maxdow</a></li>
				
			</ul>
			<p>Thanks a bunch, y'all!</p>	
		</div>
	</div>
</div>